http:
  listen: 127.0.0.1:19060
buntdb:
  path: build/package/api-gateway.db
security:
  jwt-secret: YzExNDViNjcxOTI4ZTMxMTYxMTJlNDJmNWUwM2U0MDEgIC0K
  authorities:
    - ROLE_ADMIN
    - ROLE_USER
    - SALES
    - DEVELOPER
services:
  smpp-simulator:
    - http://127.0.0.1:19061
  traffic-generator:
    - http://127.0.0.1:19063
# S3 File Storage for configuration repositories
s3:
  endpoint: "play.min.io"
  accessKeyID: "Q3AM3UQ867SPQQA43P2F"
  secretAccessKey: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
  useSSL: true
  bucket: "smpptools"        