http:
  listen: 127.0.0.1:19063
buntdb:
  path: build/package/bunt.db
  user-db: build/package/user.db
security:
  jwt-secret: YzExNDViNjcxOTI4ZTMxMTYxMTJlNDJmNWUwM2U0MDEgIC0K
  authorities:
    - ROLE_ADMIN
    - ROLE_USER
    - SALES
    - DEVELOPER
smpp:
  client:
    bind:
      bindType: "transceiver"
      connection:
        addr: "staging.soibe.xyz:12346"
        systemID: "test"
        password: "test"
        systemType: ""
        addrTon: 0
        addrNpi: 0
        addrRange: "1234"
# S3 File Storage for configuration repositories
s3:
  endpoint: "play.min.io"
  accessKeyID: "Q3AM3UQ867SPQQA43P2F"
  secretAccessKey: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
  useSSL: true
  bucket: "smpptools"        